// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxXYNONKAtrjD7DDg6MCdEDU0l-tOk7pA',
    appId: '1:219271250664:web:0d5431770e60ca6e743f5d',
    messagingSenderId: '219271250664',
    projectId: 'chat-app-d79ed',
    authDomain: 'chat-app-d79ed.firebaseapp.com',
    storageBucket: 'chat-app-d79ed.appspot.com',
    measurementId: 'G-RLQ6MSP05G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjjwP5vfo8wJC8WtwGK4RXkzH6PuVQby0',
    appId: '1:219271250664:android:d60a71805b02b352743f5d',
    messagingSenderId: '219271250664',
    projectId: 'chat-app-d79ed',
    storageBucket: 'chat-app-d79ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjKJl29qn4yIqeJZkscrqxFbblmfLe08E',
    appId: '1:219271250664:ios:fa08d0a54dab8d1c743f5d',
    messagingSenderId: '219271250664',
    projectId: 'chat-app-d79ed',
    storageBucket: 'chat-app-d79ed.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjKJl29qn4yIqeJZkscrqxFbblmfLe08E',
    appId: '1:219271250664:ios:b3ef40f5d676fe86743f5d',
    messagingSenderId: '219271250664',
    projectId: 'chat-app-d79ed',
    storageBucket: 'chat-app-d79ed.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
